config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'search#show'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to:'users#new'
  get '/about', to: "pages#about"
  root "pages#home"

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :songs, only: [:show]
  resources :artists, only: [:show]
  resources :categories, only: [:show]
  resources :favourites, only: [:show, :update]
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_many :songs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :albums
  has_many :songs
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :songs
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :song
  belongs_to :user
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  belongs_to :album
  has_and_belongs_to_many :categories
  has_many :favourites
  has_many :users, through: :favourites
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token

  has_many :favourites
  has_many :songs, through: :favourites

  before_save { self.email = email.downcase }
  before_create :create_activation_digest
  validates :name, presence: {message: '이름을 입력하세요'}, length: { maximum: 50, message: '이름은 최대 50자로 입력하세요' }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: {message: '이메일 주소를 입력하세요'}, length: { maximum: 255, message: '이메일 주소는 최대 255자로 입력하세요' },
    format: { with: VALID_EMAIL_REGEX, message: '올바른 이메일 주소를 입력하세요.' }, uniqueness: {message: '이미 사용 중인 이메일 주소입니다'}

  has_secure_password
  validates :password, presence: true, length: { minimum: 6, message: '비밀번호를 최소 6자로 입력하세요' }

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  # Returns true if the given token matches the digest
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @albums = Album.limit(5).order("RANDOM()")
    @categories = Category.all
    @songs = Song.limit(10).order('views DESC')
    @artists = Artist.limit(10).order('views DESC')
    @songs_new = Song.limit(10).order('created_at DESC')
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def show
    if params[:query].blank?
      flash[:danger] = '검색어를 입력하세요'
      redirect_to root_url and return
    else
      query = Song.sanitize_sql_like(params[:query].downcase)
      @artists = Artist.where('lower(original_name) LIKE ?', "#{query}%").or(
        Artist.where('lower(korean_name) LIKE ?', "#{query}%"))
      @songs = Song.where('lower(title) LIKE ?', "%#{query}%")
      @artist_songs = []
      if !@artists.empty?
        @artists.each do |artist|
          @artist_songs << artist.songs
        end
      end
    end
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def show
    @song = Song.find(params[:id])
    @song.views += 1
    @song.save
    @album = @song.album
    if logged_in?
      @favourite_exists = Favourite.where(song_id: params[:id], user_id: current_user.id) == [] ? false : true
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.where(activated: true).paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    redirect_to root_url and return unless @user.activated == true
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # code for account activation
      # @user.send_activation_email
      # flash[:success] = "Please check your email to activate your account"
      # redirect_to root_url
      @user.activate
      log_in @user
      redirect_to @user
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "프로필이 수정되었습니다"
      redirect_to @user
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "회원이 삭제되었습니다"
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "로그인을 해주세요"
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(title = '')
        base_title = "기타 코드 악보"
        if title.empty?
            base_title
        else
            title + ' | ' + base_title
        end
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
  def favourite_text
    return @favourite_exists ? '즐겨찾기에서 제거' : '즐겨찾기에 추가'
  end
  def favourite_class
    return @favourite_exists ? 'glyphicon glyphicon-star' : 'glyphicon glyphicon-star-empty'
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.encrypted[:user_id] = user.id
    cookies.permanent.encrypted[:remember_token] = user.remember_token
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: session[:user_id])
    elsif (user_id = cookies.encrypted[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def current_user?(user)
    user && user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    size = options[:size]
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/layouts/_categories.html.erb
<div class="list-group">
  <div class="list-group-item active lead"><strong>카테고리 / 장르</strong></div>
  <% categories.each do |category| %>
    <%= link_to category, class: 'list-group-item' do %>
      <h4><strong><%= category.name %></strong></h4>
    <% end %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>기타 코드 악보 사이트 by 강동현</small>
  <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
  <%= link_to image_tag("logos/logo_small.png", class:"navbar-brand", width:"180"), root_path %>
    <nav>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
                data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1"
                aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <ul class="nav navbar-nav navbar-right collapse navbar-collapse"
          id="bs-example-navbar-collapse-1">  
        <li><%= link_to "홈", root_path %></li>
        <li><%= link_to "사이트 소개", about_path %></li>
        <% if logged_in? %>
          <li><%= link_to "회원 목록", users_path %></li>
          <li><%= link_to "즐겨찾기", favourite_path(current_user.id) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" type="button" data-toggle="dropdown">
              계정 <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "프로필", current_user %></li>
              <li><%= link_to "설정", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "로그아웃", logout_path, data: { turbo_method: :delete } %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "로그인", login_path %></li>
        <% end %>
        <li><%= render 'search/form' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= yield :head %>
    <%= favicon_link_tag asset_path('logos/favicon.ico') %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>    
    </div>
  </body>
</html>

app/views/pages/_carousel.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
    <li data-target="#myCarousel" data-slide-to="4"></li>
  </ol>
  <div class="carousel-inner">
    <% albums.each_with_index do |album, index| %>
      <div class="<%= index==0 ? "item active" : "item" %>">
        <%= link_to album.songs.first do %>
          <%= image_tag "albums/#{album.img_location}" %>
          <div class="carousel-caption">
            <h3><%= album.songs.first.title %></h3>
            <h4><%= album.artist.korean_name %></h4>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/pages/_rankings.html.erb
<div class="list-group">
  <div class="list-group-item active lead"><strong><%= msg %></strong></div>
  <% arr.each_with_index do |var, index| %>
    <%= link_to var, class: 'list-group-item' do %>
      <h4>
        <strong class="text-primary"><%= index+1 %>. </strong>
        <% if msg=="Top 10 악보 랭킹" || msg=="최신악보" %>
          <strong><%= var.title %></strong> - <%= var.artist.korean_name %>
        <% else %>
          <strong><%= var.korean_name %></strong>
        <% end %>
      </h4>
    <% end %>
  <% end %>
</div>

app/views/pages/about.html.erb
<% provide(:title, 'About') %>
<div class="jumbotron">
  <h1>About</h1>
  <h2>
    무료 기타 코드 악보 사이트입니다. Github 페이지는 
    <a href="https://github.com/peterkang98/guitar-chord-rails-app-aws">여기에서</a> 볼 수 있습니다.
  </h2>
  <h3><strong><u>주요 기능</u></strong></h3>
  <ul class="lead">
    <li><strong>곡 제목 또는 가수명으로 검색 가능</strong></li>
    <li><strong>악보 즐겨찾기(회원인 경우)</strong></li>
    <li><strong>인기 악보, 인기 가수 순위</strong></li>
    <li><strong>음악 장르 카테고리</strong></li>
    <li><strong>악보 자동 스크롤, 속도 조절(노래의 BPM에 맞출 수도 있음)</strong></li>
    <li><strong>악보 키 조절</strong></li>
    <li><strong>카포 위치 조절</strong></li>
  </ul>
</div>

app/views/pages/home.html.erb
<div class="row">
  <div class="center jumbotron">
    <h1>기타 코드 악보 사이트에 오신 것을 환영합니다!</h1>
    <h2>
      무료로 악보를 제공하며, PC와 모바일 모두 호환 가능합니다.
    </h2>
    <%= link_to "회원가입", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
</div>
<div class="row">
  <div class="well col-sm-6">
    <%= render partial: "carousel", locals: { albums: @albums } %>
  </div>
  <div class="col-sm-6">
    <%= render partial: "layouts/categories", locals: { categories: @categories } %>
  </div>
</div>
<div class="row">
  <div class="col-sm-6">
    <%= render partial: "rankings", locals: { msg: 'Top 10 악보 랭킹' , arr: @songs } %>
  </div>
</div>
<div class="row">
  <div class="col-sm-6">
    <%= render partial: "rankings", locals: { msg: 'Top 10 아티스트 랭킹' , arr: @artists } %>
  </div>
</div>
<div class="row">
  <div class="col-sm-6">
    <%= render partial: "rankings", locals: { msg: '최신악보' , arr: @songs_new } %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      오류가 <%= @user.errors.count %>개 있습니다..
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>